// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieReservationAPI.Models.Auth;

#nullable disable

namespace MovieReservationAPI.Migrations
{
    [DbContext(typeof(MovieContext))]
    [Migration("20260215153004_InitialModels")]
    partial class InitialModels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("MovieReservationAPI.Models.Auth.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("MovieReservationAPI.Models.Entities.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Genres");
                });

            modelBuilder.Entity("MovieReservationAPI.Models.Entities.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Movies");
                });

            modelBuilder.Entity("MovieReservationAPI.Models.Entities.MovieGenre", b =>
                {
                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.HasKey("MovieId", "GenreId");

                    b.HasIndex("GenreId");

                    b.ToTable("MovieGenre");
                });

            modelBuilder.Entity("MovieReservationAPI.Models.Entities.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ReservedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("SeatId")
                        .HasColumnType("int");

                    b.Property<int>("ShowtimeId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("SeatId");

                    b.HasIndex("UserId");

                    b.HasIndex("ShowtimeId", "SeatId")
                        .IsUnique();

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("MovieReservationAPI.Models.Entities.Seat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<string>("Row")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Row", "Number")
                        .IsUnique();

                    b.ToTable("Seats");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Number = 1,
                            Row = "A"
                        },
                        new
                        {
                            Id = 2,
                            Number = 2,
                            Row = "A"
                        },
                        new
                        {
                            Id = 3,
                            Number = 3,
                            Row = "A"
                        },
                        new
                        {
                            Id = 4,
                            Number = 4,
                            Row = "A"
                        },
                        new
                        {
                            Id = 5,
                            Number = 5,
                            Row = "A"
                        },
                        new
                        {
                            Id = 6,
                            Number = 6,
                            Row = "A"
                        },
                        new
                        {
                            Id = 7,
                            Number = 7,
                            Row = "A"
                        },
                        new
                        {
                            Id = 8,
                            Number = 8,
                            Row = "A"
                        },
                        new
                        {
                            Id = 9,
                            Number = 9,
                            Row = "A"
                        },
                        new
                        {
                            Id = 10,
                            Number = 10,
                            Row = "A"
                        },
                        new
                        {
                            Id = 11,
                            Number = 1,
                            Row = "B"
                        },
                        new
                        {
                            Id = 12,
                            Number = 2,
                            Row = "B"
                        },
                        new
                        {
                            Id = 13,
                            Number = 3,
                            Row = "B"
                        },
                        new
                        {
                            Id = 14,
                            Number = 4,
                            Row = "B"
                        },
                        new
                        {
                            Id = 15,
                            Number = 5,
                            Row = "B"
                        },
                        new
                        {
                            Id = 16,
                            Number = 6,
                            Row = "B"
                        },
                        new
                        {
                            Id = 17,
                            Number = 7,
                            Row = "B"
                        },
                        new
                        {
                            Id = 18,
                            Number = 8,
                            Row = "B"
                        },
                        new
                        {
                            Id = 19,
                            Number = 9,
                            Row = "B"
                        },
                        new
                        {
                            Id = 20,
                            Number = 10,
                            Row = "B"
                        },
                        new
                        {
                            Id = 21,
                            Number = 1,
                            Row = "C"
                        },
                        new
                        {
                            Id = 22,
                            Number = 2,
                            Row = "C"
                        },
                        new
                        {
                            Id = 23,
                            Number = 3,
                            Row = "C"
                        },
                        new
                        {
                            Id = 24,
                            Number = 4,
                            Row = "C"
                        },
                        new
                        {
                            Id = 25,
                            Number = 5,
                            Row = "C"
                        },
                        new
                        {
                            Id = 26,
                            Number = 6,
                            Row = "C"
                        },
                        new
                        {
                            Id = 27,
                            Number = 7,
                            Row = "C"
                        },
                        new
                        {
                            Id = 28,
                            Number = 8,
                            Row = "C"
                        },
                        new
                        {
                            Id = 29,
                            Number = 9,
                            Row = "C"
                        },
                        new
                        {
                            Id = 30,
                            Number = 10,
                            Row = "C"
                        },
                        new
                        {
                            Id = 31,
                            Number = 1,
                            Row = "D"
                        },
                        new
                        {
                            Id = 32,
                            Number = 2,
                            Row = "D"
                        },
                        new
                        {
                            Id = 33,
                            Number = 3,
                            Row = "D"
                        },
                        new
                        {
                            Id = 34,
                            Number = 4,
                            Row = "D"
                        },
                        new
                        {
                            Id = 35,
                            Number = 5,
                            Row = "D"
                        },
                        new
                        {
                            Id = 36,
                            Number = 6,
                            Row = "D"
                        },
                        new
                        {
                            Id = 37,
                            Number = 7,
                            Row = "D"
                        },
                        new
                        {
                            Id = 38,
                            Number = 8,
                            Row = "D"
                        },
                        new
                        {
                            Id = 39,
                            Number = 9,
                            Row = "D"
                        },
                        new
                        {
                            Id = 40,
                            Number = 10,
                            Row = "D"
                        },
                        new
                        {
                            Id = 41,
                            Number = 1,
                            Row = "E"
                        },
                        new
                        {
                            Id = 42,
                            Number = 2,
                            Row = "E"
                        },
                        new
                        {
                            Id = 43,
                            Number = 3,
                            Row = "E"
                        },
                        new
                        {
                            Id = 44,
                            Number = 4,
                            Row = "E"
                        },
                        new
                        {
                            Id = 45,
                            Number = 5,
                            Row = "E"
                        },
                        new
                        {
                            Id = 46,
                            Number = 6,
                            Row = "E"
                        },
                        new
                        {
                            Id = 47,
                            Number = 7,
                            Row = "E"
                        },
                        new
                        {
                            Id = 48,
                            Number = 8,
                            Row = "E"
                        },
                        new
                        {
                            Id = 49,
                            Number = 9,
                            Row = "E"
                        },
                        new
                        {
                            Id = 50,
                            Number = 10,
                            Row = "E"
                        },
                        new
                        {
                            Id = 51,
                            Number = 1,
                            Row = "F"
                        },
                        new
                        {
                            Id = 52,
                            Number = 2,
                            Row = "F"
                        },
                        new
                        {
                            Id = 53,
                            Number = 3,
                            Row = "F"
                        },
                        new
                        {
                            Id = 54,
                            Number = 4,
                            Row = "F"
                        },
                        new
                        {
                            Id = 55,
                            Number = 5,
                            Row = "F"
                        },
                        new
                        {
                            Id = 56,
                            Number = 6,
                            Row = "F"
                        },
                        new
                        {
                            Id = 57,
                            Number = 7,
                            Row = "F"
                        },
                        new
                        {
                            Id = 58,
                            Number = 8,
                            Row = "F"
                        },
                        new
                        {
                            Id = 59,
                            Number = 9,
                            Row = "F"
                        },
                        new
                        {
                            Id = 60,
                            Number = 10,
                            Row = "F"
                        },
                        new
                        {
                            Id = 61,
                            Number = 1,
                            Row = "G"
                        },
                        new
                        {
                            Id = 62,
                            Number = 2,
                            Row = "G"
                        },
                        new
                        {
                            Id = 63,
                            Number = 3,
                            Row = "G"
                        },
                        new
                        {
                            Id = 64,
                            Number = 4,
                            Row = "G"
                        },
                        new
                        {
                            Id = 65,
                            Number = 5,
                            Row = "G"
                        },
                        new
                        {
                            Id = 66,
                            Number = 6,
                            Row = "G"
                        },
                        new
                        {
                            Id = 67,
                            Number = 7,
                            Row = "G"
                        },
                        new
                        {
                            Id = 68,
                            Number = 8,
                            Row = "G"
                        },
                        new
                        {
                            Id = 69,
                            Number = 9,
                            Row = "G"
                        },
                        new
                        {
                            Id = 70,
                            Number = 10,
                            Row = "G"
                        },
                        new
                        {
                            Id = 71,
                            Number = 1,
                            Row = "H"
                        },
                        new
                        {
                            Id = 72,
                            Number = 2,
                            Row = "H"
                        },
                        new
                        {
                            Id = 73,
                            Number = 3,
                            Row = "H"
                        },
                        new
                        {
                            Id = 74,
                            Number = 4,
                            Row = "H"
                        },
                        new
                        {
                            Id = 75,
                            Number = 5,
                            Row = "H"
                        },
                        new
                        {
                            Id = 76,
                            Number = 6,
                            Row = "H"
                        },
                        new
                        {
                            Id = 77,
                            Number = 7,
                            Row = "H"
                        },
                        new
                        {
                            Id = 78,
                            Number = 8,
                            Row = "H"
                        },
                        new
                        {
                            Id = 79,
                            Number = 9,
                            Row = "H"
                        },
                        new
                        {
                            Id = 80,
                            Number = 10,
                            Row = "H"
                        },
                        new
                        {
                            Id = 81,
                            Number = 1,
                            Row = "I"
                        },
                        new
                        {
                            Id = 82,
                            Number = 2,
                            Row = "I"
                        },
                        new
                        {
                            Id = 83,
                            Number = 3,
                            Row = "I"
                        },
                        new
                        {
                            Id = 84,
                            Number = 4,
                            Row = "I"
                        },
                        new
                        {
                            Id = 85,
                            Number = 5,
                            Row = "I"
                        },
                        new
                        {
                            Id = 86,
                            Number = 6,
                            Row = "I"
                        },
                        new
                        {
                            Id = 87,
                            Number = 7,
                            Row = "I"
                        },
                        new
                        {
                            Id = 88,
                            Number = 8,
                            Row = "I"
                        },
                        new
                        {
                            Id = 89,
                            Number = 9,
                            Row = "I"
                        },
                        new
                        {
                            Id = 90,
                            Number = 10,
                            Row = "I"
                        },
                        new
                        {
                            Id = 91,
                            Number = 1,
                            Row = "J"
                        },
                        new
                        {
                            Id = 92,
                            Number = 2,
                            Row = "J"
                        },
                        new
                        {
                            Id = 93,
                            Number = 3,
                            Row = "J"
                        },
                        new
                        {
                            Id = 94,
                            Number = 4,
                            Row = "J"
                        },
                        new
                        {
                            Id = 95,
                            Number = 5,
                            Row = "J"
                        },
                        new
                        {
                            Id = 96,
                            Number = 6,
                            Row = "J"
                        },
                        new
                        {
                            Id = 97,
                            Number = 7,
                            Row = "J"
                        },
                        new
                        {
                            Id = 98,
                            Number = 8,
                            Row = "J"
                        },
                        new
                        {
                            Id = 99,
                            Number = 9,
                            Row = "J"
                        },
                        new
                        {
                            Id = 100,
                            Number = 10,
                            Row = "J"
                        });
                });

            modelBuilder.Entity("MovieReservationAPI.Models.Entities.Showtime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.ToTable("Showtimes");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("MovieReservationAPI.Models.Auth.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("MovieReservationAPI.Models.Auth.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieReservationAPI.Models.Auth.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("MovieReservationAPI.Models.Auth.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MovieReservationAPI.Models.Entities.MovieGenre", b =>
                {
                    b.HasOne("MovieReservationAPI.Models.Entities.Genre", "Genre")
                        .WithMany("MovieGenres")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieReservationAPI.Models.Entities.Movie", "Movie")
                        .WithMany("MovieGenres")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("MovieReservationAPI.Models.Entities.Reservation", b =>
                {
                    b.HasOne("MovieReservationAPI.Models.Entities.Seat", "Seat")
                        .WithMany("Reservations")
                        .HasForeignKey("SeatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieReservationAPI.Models.Entities.Showtime", "Showtime")
                        .WithMany("Reservations")
                        .HasForeignKey("ShowtimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieReservationAPI.Models.Auth.AppUser", "User")
                        .WithMany("Reservations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Seat");

                    b.Navigation("Showtime");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MovieReservationAPI.Models.Entities.Showtime", b =>
                {
                    b.HasOne("MovieReservationAPI.Models.Entities.Movie", "Movie")
                        .WithMany("Showtimes")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("MovieReservationAPI.Models.Auth.AppUser", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("MovieReservationAPI.Models.Entities.Genre", b =>
                {
                    b.Navigation("MovieGenres");
                });

            modelBuilder.Entity("MovieReservationAPI.Models.Entities.Movie", b =>
                {
                    b.Navigation("MovieGenres");

                    b.Navigation("Showtimes");
                });

            modelBuilder.Entity("MovieReservationAPI.Models.Entities.Seat", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("MovieReservationAPI.Models.Entities.Showtime", b =>
                {
                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
